version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - postgres_app:/usr/src/app/
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=POSTGRES_USER_env
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD_env
      - POSTGRES_DB=POSTGRES_DB_env
volumes:
  postgres_data:
  postgres_app: